[managers]
esgi-2603-my-favorite-places-manager-1

[managers:vars]
ansible_connection=community.docker.docker

[workers]
esgi-2603-my-favorite-places-node-1
esgi-2603-my-favorite-places-node-2
esgi-2603-my-favorite-places-node-3

[workers:vars]
ansible_connection=community.docker.docker
